package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"gin-auth-mongo/graph"
	"gin-auth-mongo/graph/model"
)

// HelloWorld is the resolver for the helloWorld field.
func (r *mutationResolver) HelloWorld(ctx context.Context) (*model.HelloWorld, error) {
	panic(fmt.Errorf("not implemented: HelloWorld - helloWorld"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
