// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"gin-auth-mongo/models"

	"github.com/99designs/gqlgen/graphql"
)

type AccessToken struct {
	AccessToken       string `json:"accessToken"`
	AccessTokenExpiry string `json:"accessTokenExpiry"`
}

type HelloWorld struct {
	Message string `json:"message"`
}

type LoginResponse struct {
	User  *models.User `json:"user"`
	Token *Token       `json:"token"`
}

type Mutation struct {
}

type Query struct {
}

type Token struct {
	UserID             string `json:"userID"`
	AccessToken        string `json:"accessToken"`
	RefreshToken       string `json:"refreshToken"`
	AccessTokenExpiry  string `json:"accessTokenExpiry"`
	RefreshTokenExpiry string `json:"refreshTokenExpiry"`
	Device             string `json:"device"`
}

type UploadAvatarRequest struct {
	Avatar graphql.Upload `json:"avatar"`
}
